name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    permissions:
      packages: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          check-latest: true
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1
      - name: List changed charts
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
      - name: Lint Charts
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}
      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1
      - name: Container Registry Secret
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          kubectl create ns test-namespace
          kubectl create secret docker-registry ghcr-login --docker-server=https://ghcr.io --docker-username=$GITHUB_USER --docker-password=${{ github.token }} -n test-namespace
      - name: Test Charts
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --namespace=test-namespace --target-branch ${{ github.event.repository.default_branch }}
